version: '2.1'

services:
    rt1:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        command: "tpcdump -nSt icmp"
    rt2:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        command: "ping -s 4000 rt1"
        depends_on:
            - rt1
    rt3:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        sysctls:
            - net.ipv4.icmp_echo_ignore_all=1
        command: "ping rt1"
        depends_on:
            - rt1
    rt4:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        command: "ping -c 1 rt3"
        depends_on:
            - rt3
networks:
    tnet2:
        ipam:
            driver: default
            config:
                - subnet: 172.111.111.0/16
                  gateway: 172.111.111.1
